export default {
  blockHeights: {
    navBar: '91px',
    hero: '50vh',
    superHero: '70vh'
  },
  breakpoints: [32, 48, 64, 80, 96],
  colors: {
    text: '#4a4a55',
    text70: '#818188',
    text40: '#b7b7bb',
    text20: '#dbdbdd',
    text10: '#ededee',
    text7: '#f2f2f3',
    brand: '#c90b50',
    brandAlt: '#404070',
    brandAlt70: '#797A9A',
    beige: '#F7F2EC',
    offBlue: '#e8f6fb',
    offWhite: '#f6f6f6',
    white: '#fff',
    grey: '#EEEEF0',
    success: '#42db41',
    error: '#D91E1F',
  },
  containers: {
    sm: '672px',
    rg: '960px',
    lg: '1140px',
  },
  fonts: {
    displayThin: 'GT-Eesti-Pro-Display-Thin',
    displayLight: 'GT-Eesti-Pro-Display-Light',
    displayRegular: 'GT-Eesti-Pro-Display-Regular',
    displayMedium: 'GT-Eesti-Pro-Display-Medium',
    textLight: 'GT-Eesti-Pro-Text-Light',
    textBook: 'GT-Eesti-Pro-Text-Book',
    textRegular: 'GT-Eesti-Pro-Text-Regular',
    textMedium: 'GT-Eesti-Pro-Text-Medium',
    textBold: 'GT-Eesti-Pro-Text-Bold',
  },
  font: 'GT-Eesti-Pro-Text',
  headlineFont: 'GT-Eesti-Pro-Display',
  fontSizes: [11, 13, 16, 18, 21, 27, 36, 48],
  letterSpacing: {
    body: '0.03em',
    text: '0.02em',
    tight: '-0.02em',
    button: '0.025em',
    touch: '0.075em',
    meta: '0.15em',
  },
  lineHeight: {
    display: '1.05',
    headline: '1.15',
    subheadline: '1.3',
    text: '1.375',
    feedback: '2.5',
  },
  space: [0, 8, 16, 32, 64, 128, 160],
}